### ISSUE TITLE
Feature: User can create an account and log in

### ISSUE THREAD

**Issue by cindy-le91** [cindy-le91/disney-itinerary-builder#1]
## ⚙️ Feature - 

> ##### What capability will users have when this feature is merged?

User can create an account and log in to website
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User will click on sign up button that takes them to a registration page where they will enter their username and password. Once they click register, they will be taken back to the main landing page to log in.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="453" alt="Screen Shot 2023-06-05 at 4 42 45 PM" src="https://github.com/cindy-le91/Disney-Itinerary-Builder/assets/79718224/51e19d66-6c08-44e5-b32c-352e090d915e">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to make the user table
- [x] Update `data.sql` to populate the user table
- [x] Implement password hashing

### ☁️ Server Tasks

- [x] Update `server.js` to make routes for user authentication
- [x] Implement session management
- [x] Add authentication middleware
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create form with buttons for sign in
- [x] Create form with buttons for sign up
- [x] Style forms to match figma designs
- [x] Create user authentication component for sign up
- [x] Create user authentication component for sign in

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
