### ISSUE TITLE
Feature: User can view lists of attractions and dining options

### ISSUE THREAD

**Issue by cindy-le91** [cindy-le91/disney-itinerary-builder#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view lists of attractions and dining options

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to navigate tabs, allowing them to view lists of attractions or dining options

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="713" alt="Screen Shot 2023-06-05 at 10 03 52 PM" src="https://github.com/cindy-le91/Disney-Itinerary-Builder/assets/79718224/2c0d459c-38f6-48e0-a344-480359d63af3">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create components for trip, dining, and attractions
- [x] Fetch dining and attraction info from theme park API
- [x] Update component to display each item under appropriate tab
- [x] Style  components to match figma designs

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
