### ISSUE TITLE
Feature: User can add attractions and dining options to itinerary

### ISSUE THREAD

**Issue by cindy-le91** [cindy-le91/disney-itinerary-builder#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add attractions and dining options to itinerary

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can add attraction or dining option to trip planner by clicking '+'; this will prompt user to enter a start time for the event

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="883" alt="Screen Shot 2023-06-05 at 10 06 33 PM" src="https://github.com/cindy-le91/Disney-Itinerary-Builder/assets/79718224/9e15624b-b94d-4ad9-a8d9-59b6506b4a3b">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to make a route to receive network requests
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to add event
- [x] Create component to add start time
- [x] Style to match figma designs

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
