### ISSUE TITLE
Feature: User can update visit times for attraction/ dining options

### ISSUE THREAD

**Issue by cindy-le91** [cindy-le91/disney-itinerary-builder#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can move items around in itinerary by changing dining/ attractions visit times
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click 3 dots on the side of each attraction or dining slot to make changes. When the edit option is click, time can be edited via dropdown. Attraction/ dining option should move to appropriate time slot.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="644" alt="Screen Shot 2023-06-05 at 10 10 28 PM" src="https://github.com/cindy-le91/Disney-Itinerary-Builder/assets/79718224/359eca3f-7dc3-4788-a2b2-e74558ee1d64">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [ ] In `server.js` to create a route that handles updates
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Revise design to add a dropdown that lets user choose option to edit
- [ ] Update component to allow event time change
- [ ] Update component to move event to proper place in schedule
- [ ] Style to match figma designs

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
